BchS_test/bcs_test/bcs_test/apps/transact/urls.py
from django.urls import path

from . import views

app_name = 'transact'
urlpatterns = [
    path('', views.transaction_send, name = 'transaction_send'),
    path('', views.index, name = 'index'),
    path('<int:transaction_id>/', views.detail, name = 'detail')
]

BchS_test/bcs_test/bcs_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('transact/', include('transact.urls')),
    path('admin/', admin.site.urls),
]

BchS_test/bcs_test/bcs_test/apps/transact/models.py
from django.db import models

class Transaction(models.Model):
    transaction_id = models.CharField('хеш транзакции', max_length = 100)
    transaction_sum = models.FloatField('сумма транзакции', max_length = 20)
    transaction_description = models.TextField('описание транзакции', max_length = 200, default="")

    def __str__(self):
        return self.transaction_id

    class Meta:
        verbose_name = "Транзакция"
        verbose_name_plural = "Транзакции"

BchS_test/bcs_test/bcs_test/apps/transact/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render
import requests
import json
from pycoin.solve.utils import build_hash160_lookup
from pycoin.ecdsa.secp256k1 import secp256k1_generator
from .models import Transaction
from . import create_transaction

def index(request):
    transaction_list = Transaction.objects.all()
    return render(request, 'transact/list.html', {'transaction_list': transaction_list})

def detail(request, transaction_id):
    try:
        t = Transaction.objects.get( id = transaction_id)
    except:
        raise Http404("Транзакци не найдена!")

    return render(request, 'transact/detail.html', {'transaction': t})

def transaction_send(request):
    url = "http://45.32.232.25:3669/wallet/testwallet"
    rpc_user = 'bcs_tester'
    rpc_password = 'iLoveBCS'
    payload = json.dumps({"method": "getnewaddress", "params": []})
    headers = {'content-type': "application/json", 'cache-control': "no-cache"}
    response = requests.request("POST", url, data=payload, headers=headers, auth=(rpc_user, rpc_password))
    address = json.loads(response.text)['result']

    tx_sum = 1000000
    tx = create_transaction.New_tx(address)

    signed_tx, signed_hex = tx.create_tx(satoshi_value=tx_sum, solver_f=build_hash160_lookup, generator=secp256k1_generator)
    print(signed_tx)
    print(signed_hex)
    payload = json.dumps({"method": "sendrawtransaction", "params": [signed_hex]})
    response = requests.request("POST", url, data=payload, headers=headers, auth=(rpc_user, rpc_password))

    tx_to_db = Transaction(transaction_id = json.loads(response.text)['txid'], transaction_sum = tx_sum, transaction_description = "")
    tx_to_db.save()

    return index(request)

BchS_test/bcs_test/bcs_test/templates/base.html
<!doctype html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Транзакции{% endblock %}</title>
	<style>
		button {
			display: inline-block;
			background: #2196f3;
			color: #fff;
			padding: 12px;
			border: none;
			border-radius: 3px;
			text-decoration: none;
			font-family: Tahoma;
			font-size: 18px;
			line-height: 1;
			font-weight: 100;
			cursor: pointer;
		}
		th {
		   border: 1px solid grey;
		}
		td {
		   border: 1px solid grey;
		}
		div {
		  margin: 24px;
		  text-align: center;
		  padding: 10px;
		}
		.trans_table{
			text-align: center;
			width: 800px;
			border: 1px solid grey;
			margin: auto;
		}
	</style>
</head>
<body>
	<form method="POST" action="{% url 'transact:transaction_send' %}">

		{% csrf_token %}

		<div style="text-align: center;">
			<button type="submit">Отправить транзакцию</button>
		</div>
		<div style="text-align: center;">
			<table class="trans_table">
				<caption>Таблица транзакций</caption>
				   <tr>
					<th>Транзакция</th>
				   </tr>
					{% block transaction %}{% endblock %}
			</table>
		</div>
	</form>
<script>
</script>
</body>
</html>

BchS_test/bcs_test/bcs_test/templates/transact/detail.html
<!doctype html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>{{transaction.transaction_hash}}</title>
	<style>
		th {
		   border: 1px solid grey;
		}
		td {
		   border: 1px solid grey;
		}
		div {
		  margin: 24px;
		  text-align: center;
		  padding: 10px;
		}
		.trans_table{
			text-align: center;
			width: 100%;
			border: 1px solid grey;
			margin: auto;
		}
	</style>
</head>
<body>
		<div style="text-align: center;">
			<table class="trans_table">
				<caption>Детали транзакции</caption>
				    <tr>
					    <th>Транзакция: {{transaction.transaction_hash}}</th>
				    </tr>
                <tr><td>Сумма транзакции : {{transaction.transaction_sum}} BCS</td></tr>
				<tr><td>Описание : {{transaction.transaction_description}}</td></tr>
			</table>
		</div>
<script>

</script>
</body>
</html>

BchS_test/bcs_test/bcs_test/templates/transact/list.html
{% extends 'base.html' %}

{% block transaction %}

    {% if transaction_list %}

        {% for t in transaction_list %}
            <tr><td><a href="{% url 'transact:detail' t.id %}">{{t.transaction_hash}}</a></td></tr>
        {% endfor %}

    {% else %}
        <tr><td>Транзакций пока нет</td></tr>
    {% endif %}

{% endblock %}
